// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5wV305uixM9tN63D7tsZVFTvbjEgWWOg',
    appId: '1:174630395597:web:4a731a81823c79eac91384',
    messagingSenderId: '174630395597',
    projectId: 'lofound',
    authDomain: 'lofound.firebaseapp.com',
    databaseURL: 'https://lofound-default-rtdb.firebaseio.com',
    storageBucket: 'lofound.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLLJAvPX1GZlZi8riEweEUs91jD40mcow',
    appId: '1:174630395597:android:52585a6f7db34ae2c91384',
    messagingSenderId: '174630395597',
    projectId: 'lofound',
    databaseURL: 'https://lofound-default-rtdb.firebaseio.com',
    storageBucket: 'lofound.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdHWBBIanRExzBiJqr20n4Xju3P8wQ3rI',
    appId: '1:174630395597:ios:b392af8c5313d25fc91384',
    messagingSenderId: '174630395597',
    projectId: 'lofound',
    databaseURL: 'https://lofound-default-rtdb.firebaseio.com',
    storageBucket: 'lofound.appspot.com',
    androidClientId: '174630395597-an2j0kap9gca9ee4rbd8k9r2mdie2jvc.apps.googleusercontent.com',
    iosClientId: '174630395597-e8ipmipc5s0fvaopa67211o4ejhl2g63.apps.googleusercontent.com',
    iosBundleId: 'com.example.lofo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5wV305uixM9tN63D7tsZVFTvbjEgWWOg',
    appId: '1:174630395597:web:8fe04372d01e9c17c91384',
    messagingSenderId: '174630395597',
    projectId: 'lofound',
    authDomain: 'lofound.firebaseapp.com',
    databaseURL: 'https://lofound-default-rtdb.firebaseio.com',
    storageBucket: 'lofound.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdHWBBIanRExzBiJqr20n4Xju3P8wQ3rI',
    appId: '1:174630395597:ios:b392af8c5313d25fc91384',
    messagingSenderId: '174630395597',
    projectId: 'lofound',
    databaseURL: 'https://lofound-default-rtdb.firebaseio.com',
    storageBucket: 'lofound.appspot.com',
    androidClientId: '174630395597-an2j0kap9gca9ee4rbd8k9r2mdie2jvc.apps.googleusercontent.com',
    iosClientId: '174630395597-e8ipmipc5s0fvaopa67211o4ejhl2g63.apps.googleusercontent.com',
    iosBundleId: 'com.example.lofo',
  );

}